### ISSUE TITLE
Relative Images

### ISSUE THREAD

**Issue by milo526** [dusterio/link-preview#12]
**URL**: http://google.com

**Response**:
```
{
  "cover": "/images/branding/googleg/1x/googleg_standard_color_128dp.png",
  "images": [],
  "title": "Google",
  "description": "",
  "video": "",
  "videoType": ""
}
```

**Code**:
```
Preview::setUrl("http://google.com");
return Preview::getPreview('general')->toArray();
```
Some sites as demonstrated above give "strange" links, these are relative and prefixing with the url doesn't work either see:  
[http://google.com/images/branding/googleg/1x/googleg_standard_color_128dp.png](http://google.com/images/branding/googleg/1x/googleg_standard_color_128dp.png)

Is there any way to prevent this behaviour and make sure all links are absolute (since there is little to no use for having relative links with this library)

**Comment by JCarlosR** [comment]
@milo526 Did you fix it?

The absolute URL that you are visiting doesn't show the image, because google.com performs a redirect. The parser goes to that domain and take the image from the last site.

For example, visiting google.com from my country, the url changes to google.com.pe and [this link][original] works.

It even works with `https://www.google.com/images/branding/googleg/1x/googleg_standard_color_128dp.png` but not visiting `https://google.com/images/branding/googleg/1x/googleg_standard_color_128dp.png`.

[original]: https://www.google.com.pe/images/branding/googleg/1x/googleg_standard_color_128dp.png
