### ISSUE TITLE
Class not found on Laravel 7

### ISSUE THREAD

**Issue by bachras** [dusterio/link-preview#23]
Hi, 

I have installed plugin via composer and try to use it on Laravel 7, but I get class not found error if I using example code:

````
"Class 'Dusterio\LinkPreview\Client' not found"
```` 

I have checked other issues and followed the suggestion in the comment:
https://github.com/dusterio/link-preview/issues/22#issuecomment-597706313

````$client = new \Dusterio\LinkPreview\LinkPreview($url);````

Then I got another class not found error:

````
"Class 'Dusterio\LinkPreview\LinkPreview' not found"
`````

I have tried to clear cache and etc but no luck.
Any help much appreciated. Thanks

**Comment by romansidorov** [comment]
Hey! Have you found any solution?

**Comment by bachras** [comment]
No, I haven't. Do you have same problem?

**Comment by ejunker** [comment]
If you look in the composer.json for this project it has:
```
"illuminate/support": "5.*|6.*",
```
which means it is not working with Laravel 7. Instead of installing the 1.2.13 version of this package composer installs an older 1.2.0 version which doesn't have the Laravel ServiceProvider and also uses an older version of Guzzle.

As far as I can tell the only thing it uses from `illuminate/support` is the ServiceProvider. Could probably change the version constraint on `illuminate/support` to `>=5` so that it keeps working with future versions of Laravel without any changes.

**Comment by ejunker** [comment]
I created this PR #25 which will need to be merged and then a new version tagged for it to work with Laravel 7. And Laravel 8 will probably be released later this month.

**Comment by dusterio** [comment]
@ejunker just merged thanks!

**Comment by ejunker** [comment]
@dusterio thank you!
